#!/bin/bash

# issue reset to make terminal wrap correctly
reset

# show motd
cat ~/.dot/motd

# load bash completion
for D in /usr/local/etc/bash_completion.d/*; do
	. $D;
done;

# source all files, in this order
for D in bash macos exports npm nvm grunt z prompt_git git svn ghwd thefuck php bashrc_Unix secret workspace; do
	source ~/.dot/$D;
done;

# symlink all .dot files
for D in ~/.dot/.*; do
	B="$(basename $D)"
	if [[ "$B" != ".git" && "$B" != "." && "$B" != ".." ]]
	then
		ln -sf .dot/$B ~/$B
	fi
done;

# source fzf
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# and we are done
echo $(date);

