#!/usr/bin/env bash

# please do not track me: https://consoledonottrack.com/
export DO_NOT_TRACK=1

# Colors
export CLICOLOR=1
export FORCE_COLOR=1

# Make vim the default editor.
export EDITOR=ex
export VISUAL=vim

# Enable persistent REPL history for `node`.
export NODE_REPL_HISTORY=~/.node_history;
# Allow 32³ entries; the default is 1000.
export NODE_REPL_HISTORY_SIZE='32768';
# Use sloppy mode by default, matching web browsers.
export NODE_REPL_MODE='sloppy';
# Allow 8Gb of RAM
export NODE_OPTIONS="--max_old_space_size=8192"

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';

# Increase Bash history size. Allow 32³ entries; the default is 500.
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}";
# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth:erasedups';

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';

# Avoid issues with `gpg` as installed via Homebrew.
# https://stackoverflow.com/a/42265848/96656
export GPG_TTY=$(tty);

# Calm npm https://twitter.com/jnybgr/status/1754838614402310645?s=12&t=TDxaJNP8GpgUlraYy3oHEA
export DISABLE_OPENCOLLECTIVE=1
export ADBLOCK=1

