#!/bin/bash

# macOS

alias l='ls -lFh'
alias la='l -a'
alias ll='ls -lh'

alias grep='grep --color'

alias o='open -a Finder .'
alias s='open -a "Sublime Text" .'
alias doc='cd ~/Documents'
alias c='open -a "Google Chrome"'
alias cc='open -a "Google Chrome Canary"'
alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias ff='open -a "Firefox"'
alias x='code .'

alias ping='prettyping --nolegend'

alias dus='ncdu --color dark -rr -x --exclude .git --exclude node_modules'

alias flushdns="dscacheutil -flushcache && killall -HUP mDNSResponder"

alias checkupdates="softwareupdate -l"
alias installupdate="sudo softwareupdate -i"
alias installupdates="installupdate -a"

alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# Fake the missing updatedb executable
alias updatedb="cd /; sudo /usr/libexec/locate.updatedb; cd - > /dev/null;"

# homebrew sbin
export PATH="/usr/local/sbin:$PATH"

# no analytics
export HOMEBREW_NO_ANALYTICS=1

