#!/bin/bash

# npmplease.com
alias npmplease="rm -rf node_modules/ && rm -f package-lock.json && npm install"
# install global deps
alias npmglobal='npm i -g diff-so-fancy eslint grunt-cli npm-check-updates trash rwh catj'
# tab completion
npm completion >> ./npm.completion
source ./npm.completion
rm -rf ./npm.completion

# Run npm format on dirty files
alias fdf="gs | egrep '[ MA]{2}' | awk '/\.(svelte|ts|js|cjs|md|css|json|yaml)$/ { system(\"dum format:file \" \$2); }'"
