#!/bin/bash

alias ss='svn status'
alias ssm='ss | grep "^[MAD]"'
alias sc='svn commit -m'
alias sup='svn up'
alias svn-clean="svn status | grep '^?' | awk '{print $2}' | xargs rm -rf"
alias svn-add="svn st | grep '^?' | sed 's/^[? ]*/\"/' | sed 's/$/\"/' | xargs svn add"
alias svn-ignore="svn propedit svn:ignore"
function sd {
	svn diff $@ | colordiff
}
function sdw {
	sd -x -w $@
}
function svnlol {
	svn log $@ | perl -l40pe 's/^-+/\n/'
}
alias scr='svn commit --non-recursive -m'
alias sup.='sup'
alias sup¸='sup'
alias sup^='sup'
alias suo='sup'

