#!/bin/bash

# subversion aliases
alias ss='svn status'
alias ssm='ss | grep "^[MAD]"'
alias sc='svn commit'
alias scm='sc -m'
alias sup='svn up'
alias svn-clean="svn status | grep '^?' | awk '{print $2}' | xargs rm -rf"
alias svn-add="svn st | grep '^?' | sed 's/^[? ]*/\"/' | sed 's/$/\"/' | xargs svn add"
alias svn-undo-del="svn status | grep '^D' | awk '{print $2}' | xargs svn revert"
alias svn-ignore="svn propedit svn:ignore"
alias svn-revert="ss | grep '^M' | xargs svn revert"

function sd {
	svn diff $@ | colordiff | diff-so-fancy
}
function sdw {
	sd -x -w $@
}
function sdeol {
	sd -x --ignore-eol-style $@
}
function sdsum {
	svn diff -r$1:HEAD --summarize
}

function svnlol {
	svn log $@ | perl -l40pe 's/^-+/\n/'
}
alias svn-lol='svnlol'

alias scr='svn commit --non-recursive -m'
alias sup.='sup'
alias sup¸='sup'
alias sup^='sup'
alias suo='sup'
