#!/bin/bash

# workspace aliases
alias w='cd workspace/assets/'
alias b='.. && ..'
alias v='jq .version package.json'
alias bn='jq .lastBuild build.json'
alias build='w;grunt;v;bn;b'
alias buildpush='sup;w;grunt build push --force;v;bn;b'

