#!/bin/bash

# workspace aliases
alias w='cd workspace/assets/'
alias b='.. && ..'
alias v='jq .version package.json'
alias bn='jq .lastBuild build.json'
alias build='w;winpty grunt.cmd;v;bn;b'
alias buildpush='sup;w;winpty grunt.cmd build push --force;v;bn;b'
